### ISSUE TITLE
[Proposal] move website to GitHub pages

### ISSUE THREAD

**Issue by SvMak** [sdkman/sdkman-website-playframework#85]
Would you like move website to GitHub pages using docs engine and current design?

This can reduce hosting costs.

**Comment by marc0der** [comment]
That sounds like a great proposal, and it would get us away from the outdated play framework too!

**Comment by SvMak** [comment]
Great, I'll do the migration and provide a demo.

**Comment by marc0der** [comment]
We need to do some minor changes to the site, like adding a new CommonHaus footer to the home page. Would you suggest we do that before or after such a migration? Also, apologies for my ignorance but how would the dynamic content be pulled in?

**Comment by SvMak** [comment]
I'll research the migration issue in more detail and report here possible solutions

And you can also make your proposal here, what you would like to improve and I will try to implement it

Is it OK for you?

**Comment by marc0der** [comment]
Sounds perfect, let me give it some thought and I'll get back to you.

**Comment by marc0der** [comment]
Okay, so I've been giving it some thought and have some feedback:

I'd like to have deep linking capability for all sections of the website, similar to what we have on the JDKs pages. That makes sharing specific things on forums much easier. For instance, sections in the installation, usage and vendors pages.

The other thing I noticed after the last update was that code blocks don't all have monospaced fonts anymore. Many blocks are falling back to the default sans fonts:

![Selection_012](https://github.com/user-attachments/assets/1bc5dc65-7e9b-4d7c-bba7-b66665712396)

Apart from those bits, it's all looking great! Anything else that the others would like to see? cc @helpermethod @eddumelendez @hgeraldino

**Comment by marc0der** [comment]
I also forgot to mention that we need to add a new footer to the landing page now that we are part of the CommonHaus Foundation. I can get more information about this, but the artwork can be [found here](https://github.com/commonhaus/artwork/tree/main/foundation/brand).

**Comment by SvMak** [comment]
> I'd like to have deep linking capability for all sections of the website, similar to what we have on the JDKs pages. That makes sharing specific things on forums much easier. For instance, sections in the installation, usage and vendors pages.

![sdkman-direct-link](https://github.com/user-attachments/assets/adef422a-3817-46c9-9e07-5d3daefe8f8e)

Do you mean direct links?

**Comment by SvMak** [comment]
> The other thing I noticed after the last update was that code blocks don't all have monospaced fonts anymore. Many blocks are falling back to the default sans fonts:

My bad, sorry(((

I'll fix it

**Comment by marc0der** [comment]
> Do you mean direct links?

I was thinking of the ability to click on the sidebar entries so that it adds (in this case) `#install` to the URL for easy sharing. We have this already on the JDKs page. The page then automatically scrolls to the correct position when clicking on the link. Or whatever you think is the best way of doing this :smile: 

It would be nice if it was consistent across all pages, though.

**Comment by SvMak** [comment]
> I was thinking of the ability to click on the sidebar entries so that it adds (in this case) `#install` to the URL for easy sharing. We have this already on the JDKs page. The page then automatically scrolls to the correct position when clicking on the link. Or whatever you think is the best way of doing this 😄
> 
> It would be nice if it was consistent across all pages, though.

OK, I understand what you mean, these are direct links, they will be

**Comment by helpermethod** [comment]
Hi!

Isn't the `Available SDK's` page generated from the DB? I don't see how we could get write of the backend service? Or we would need to statically generate that page periodically.

**Comment by marc0der** [comment]
It doesn't change very often, so we could generate it at build time perhaps. I'm guessing @SvMak already has a trick up his sleeve :smile:

**Comment by SvMak** [comment]
> Hi!
> 
> Isn't the `Available SDK's` page generated from the DB? I don't see how we could get write of the backend service? Or we would need to statically generate that page periodically.



> It doesn't change very often, so we could generate it at build time perhaps. I'm guessing @SvMak already has a trick up his sleeve 😄

Yes, we can generate page during build and I think for automation we can use GitHub API to regenerate website after update SDKs.

**Comment by SvMak** [comment]
@marc0der

To get a list of SDKs, can I use JSON API or should I use the old one (text) for now?

**Comment by SvMak** [comment]
@marc0der @helpermethod @eddumelendez @hgeraldino

Demo: https://sdkman.artspacing.com/

Basic auth:
username: User
pass: pRw8vBER44keFg

**Comment by helpermethod** [comment]
@SvMak That looks amazing! Great work!

**Comment by SvMak** [comment]
> @SvMak That looks amazing! Great work!

Thank you!

To move the code to SDKMAN! I can send an invite to a private repository or make a transfer ownership to a member of the SDKMAN! organization.

![Screenshot 2024-08-11 at 20 28 16](https://github.com/user-attachments/assets/17f4492c-4b29-40c3-9384-abea3be72a69)

**Comment by marc0der** [comment]
@SvMak I'm totally blown away by this! Thank you so much for making this happen!!!

**Comment by SvMak** [comment]
You welcome!

I sent you an invite to a private repository or I can do a repository transfer ownership

When the repository is in the organization, we will need to add a GitHub workflow for testing and deployment. We can take [this](https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions) as a basis.

After moving to the new site, I would like to improve UI even more. But this is still in the plans.

**Comment by marc0der** [comment]
Sounds great, I'll look into that later today.

**Comment by SvMak** [comment]
@marc0der

What we need to do to move the repo to the SDKMAN! organization?

**Comment by marc0der** [comment]
@SvMak So I think you need to transfer ownership to the org. Then I will add you to the repo so that you can make changes. I can hop onto discord later today or tomorrow and we can work it through together if you like.

**Comment by SvMak** [comment]
> @SvMak So I think you need to transfer ownership to the org. Then I will add you to the repo so that you can make changes. I can hop onto discord later today or tomorrow and we can work it through together if you like.

Sounds great, thank you!

**Comment by SvMak** [comment]
> @SvMak So I think you need to transfer ownership to the org. Then I will add you to the repo so that you can make changes. I can hop onto discord later today or tomorrow and we can work it through together if you like.

@marc0der 

There is already a repository with this name in SDKMAN!
Ideally, the old repo will be renamed, now I renamed the new repo.

I can transfer the ownership to someone from the organization, because I do not have the permission to create repositories in the organization.

Edit: Or you can unarchive the old repo and I can make the PR replace all the code

**Comment by marc0der** [comment]
@SvMak I've renamed the existing website to `sdkman-website-old`, so you can initiate the transfer. Does that work for you?

**Comment by SvMak** [comment]
> @SvMak I've renamed the existing website to `sdkman-website-old`, so you can initiate the transfer. Does that work for you?

@marc0der 

I meant that, but it's not critical

![Screenshot 2024-08-19 at 20 23 24](https://github.com/user-attachments/assets/c29fb973-c6c9-4167-897b-b837f44747a7)

I don't have permissions to create repos in the org, so I suggested alternatives https://github.com/sdkman/sdkman-website-old/issues/85#issuecomment-2295215220

> I can transfer the ownership to someone from the organization
> Edit: Or you can unarchive the old repo and I can make the PR replace all the code (I meant sdkman.gihub.io)

![Screenshot 2024-08-19 at 20 24 00](https://github.com/user-attachments/assets/15941fb4-a1c3-4367-8363-73add5506994)
